<template>
  <div v-if="loading" class="loading-page">
    <div class="loadingio-spinner-dual-ring-esqxx7aru1n">
      <div class="ldio-0hcja9157qci">
        <div></div>
        <div><div></div></div>
      </div>
    </div>
    <p>Loading...</p>
  </div>
</template>

<script>
export default {
  data: () => ({
    loading: false,
  }),
  methods: {
    start() {
      this.loading = true;
    },
    finish() {
      this.loading = false;
    },
  },
};
</script>


<style lang="css" scoped>
@keyframes ldio-0hcja9157qci {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-0hcja9157qci div {
  box-sizing: border-box !important;
}
.ldio-0hcja9157qci > div {
  position: absolute;
  width: 41px;
  height: 41px;
  top: 61.49999999999999px;
  left: 61.49999999999999px;
  border-radius: 50%;
  border: 4.92px solid #000;
  border-color: #007bff transparent #007bff transparent;
  animation: ldio-0hcja9157qci 0.5555555555555556s linear infinite;
}
.ldio-0hcja9157qci > div:nth-child(2) {
  border-color: transparent;
}
.ldio-0hcja9157qci > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-0hcja9157qci > div:nth-child(2) div:before,
.ldio-0hcja9157qci > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 4.92px;
  height: 4.92px;
  top: -4.92px;
  left: 13.12px;
  background: #007bff;
  border-radius: 50%;
  box-shadow: 0 36.08px 0 0 #007bff;
}
.ldio-0hcja9157qci > div:nth-child(2) div:after {
  left: -4.92px;
  top: 13.12px;
  box-shadow: 36.08px 0 0 0 #007bff;
}
.loadingio-spinner-dual-ring-esqxx7aru1n {
  width: 164px;
  height: 164px;
  display: inline-block;
  overflow: hidden;
}
.ldio-0hcja9157qci {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0hcja9157qci div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>

<style scoped>
.loading-page {
  z-index: 1000000000;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(30, 32, 35, 0.6);
  text-align: center;
  padding-top: 200px;
  font-size: 30px;
  font-family: sans-serif;
}
</style>